// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHl1nqwJsa8qiLeM0dvZ7b1qeACnBpd58',
    appId: '1:657832271973:web:cad92cd828e5de7501e68c',
    messagingSenderId: '657832271973',
    projectId: 'assessment-2de2c',
    authDomain: 'assessment-2de2c.firebaseapp.com',
    storageBucket: 'assessment-2de2c.firebasestorage.app',
    measurementId: 'G-W4W84Q3CQB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB91X6x770ocNU69FohRdiTlhanmCvU5DY',
    appId: '1:657832271973:android:eb205bfaac27cf9701e68c',
    messagingSenderId: '657832271973',
    projectId: 'assessment-2de2c',
    storageBucket: 'assessment-2de2c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbo7RGCnLfK0cWOoixoUms3CIEKSQP_yw',
    appId: '1:657832271973:ios:fa97334cf2ebd02e01e68c',
    messagingSenderId: '657832271973',
    projectId: 'assessment-2de2c',
    storageBucket: 'assessment-2de2c.firebasestorage.app',
    iosBundleId: 'com.example.auvnetFlutterInternshipAssessment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbo7RGCnLfK0cWOoixoUms3CIEKSQP_yw',
    appId: '1:657832271973:ios:fa97334cf2ebd02e01e68c',
    messagingSenderId: '657832271973',
    projectId: 'assessment-2de2c',
    storageBucket: 'assessment-2de2c.firebasestorage.app',
    iosBundleId: 'com.example.auvnetFlutterInternshipAssessment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAHl1nqwJsa8qiLeM0dvZ7b1qeACnBpd58',
    appId: '1:657832271973:web:baeef756ff7c23e101e68c',
    messagingSenderId: '657832271973',
    projectId: 'assessment-2de2c',
    authDomain: 'assessment-2de2c.firebaseapp.com',
    storageBucket: 'assessment-2de2c.firebasestorage.app',
    measurementId: 'G-J6EYEMJGRT',
  );
}
